version: 1
checks:
    - name: check
      run: npm run check
    - name: build
      run: npm run build
insults:
    mode: snarky
    file: .buildbouncer/assets/insults/default.json
    locale: en
banter:
    file: .buildbouncer/assets/banter/default.json
    locale: en
